### PR TITLE
switch from ROOT to path.resolve()

### PR DESCRIPTION
**Pull request by jonathanong**
- path.resolve() automatically resolves based on cwd()
- path.resolve() takes into account when the filename is "absolute"
- path.resolve() supports windows lol

breaking change:

- files should not start with `/` unless the path is actually at the root

### CODE REVIEW

**Comment by jonathanong** [comment]
main goal here is i want to use the config in a different module:

```js
const config = require('contracts/contractConfig.json')
// because it's currently `/`, which won't work as i'm using it as a file
// NOTE: don't remember the exact folder structure
config.file = path.resolve(require.resolve('contracts/contractConfig.json', '../contracts/contract.sol')
deployFromConfig(config)
  .then(() => console.log('done!'), err => console.error(err.stack))
```

**Comment by skmgoldin** [comment]
> path.resolve() supports windows lol

lol.

@jonathanong I merged some stuff to master before I saw this PR. Rebase on master and I'll merge this. Thanks for documenting the breaking change.

**Comment by jonathanong** [comment]
@skmgoldin k updated. fixed some error handling issues as well.

getting the following error when running tests:

```
  1) index.js using a single contract with no dependencies... #compileAndDeployFromConfig(configPath) "before all" hook:
     Error: Error: could not unlock signer account
    at StateManager.queueTransaction (/Users/jong/Workspace/adchain/testrpc/lib/statemanager.js:250:21)
    at GethApiDouble.eth_sendTransaction (/Users/jong/Workspace/adchain/testrpc/lib/subproviders/geth_api_double.js:226:14)
    at GethApiDouble.handleRequest (/Users/jong/Workspace/adchain/testrpc/lib/subproviders/geth_api_double.js:61:10)
    at next (/Users/jong/Workspace/adchain/testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at SolcSubprovider.handleRequest (/Users/jong/Workspace/adchain/testrpc/node_modules/web3-provider-engine/subproviders/solc.js:28:7)
    at next (/Users/jong/Workspace/adchain/testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at VmSubprovider.handleRequest (/Users/jong/Workspace/adchain/testrpc/node_modules/web3-provider-engine/subproviders/vm.js:40:12)
    at next (/Users/jong/Workspace/adchain/testrpc/node_modules/web3-provider-engine/index.js:95:18)
    at GethDefaults.handleRequest (/Users/jong/Workspace/adchain/testrpc/lib/subproviders/gethdefaults.js:17:12)
    at next (/Users/jong/Workspace/adchain/testrpc/node_modules/web3-provider-engine/index.js:95:18)
```

maybe i need to use a different rpc server?

**Comment by skmgoldin** [comment]
Tests pass for me. Merging, thanks!

**Pull request merged**
